dnf_packages:
  - autoconf
  - automake
  - binutils
  - bison
  - flex
  - gcc
  - gcc-c++
  - glibc-devel
  - libtool
  - make
  - ctags
  - cmake
  - clang
  - gnome-tweak-tool
  - emacs
  - clang
  - kernel-devel
  - kernel-headers
  - htop
  - powerline-fonts
  - tidy
  - gitk
  - cmake
  - ripgrep
  - meld
  - cppcheck
  - emacs
  - gdb
  - chromium
  - ruby
  - gvim
  - vim-enhanced
  - vim-X11
  - kdiff3
  - sqlite
  - sqlitebrowser
  - golang
  - vagrant
  - virt-manager
  - virt-viewer
  - nmap
  - tmux
  - xsel
  - irssi
  - weechat
  - mutt
  - git
  - vim-enhanced
  - aspell
  - aspell-en
  - jq
  - python3
  - python3-devel
  - python3-virtualenv
  - python3-bcc
  - python3-firewall
  - golang
  - golang-x-tools-gopls
  - bpftrace
  - bpftool
  - strace
  - bcc
  - bcc-tools
  - ruby
  - gcc
  - gcc-c++
  - automake
  - autoconf
  - make
  - cmake
  - libtool
  - setools-console
  - policycoreutils-python-utils
  - setroubleshoot
  - setroubleshoot-plugins
  - setroubleshoot-server
  - gnome-tweaks
  - pcp-system-tools
  - lm_sensors
  - powertop
  - iotop
  - procps-ng
  - crypto-policies
  - firewalld
  - virt-manager
  - virt-viewer
  - fuse-overlayfs
  - vinagre
  - toolbox
  - firefox-wayland
  - htop
  - mosh
  - tig
  - fpaste
  - ack
  - earlyoom
  - mediawriter
  - smartmontools
  - selinux-policy-doc
  - ibm-plex-mono-fonts
  - curl
  - gnupg
  - tcpdump
  - screen
  - kernel-doc
  - dstat
  
